# Site settings
title: Guía de Datos Abiertos para México
email: hola@datos.gob.mx
description: >
  En datos.gob.mx puedes descargar y utilizar libremente datos abiertos
  que el Gobierno de la República genera y recolecta.
baseurl: "/guia"
url: "http://10.20.55.7/"
cdn_url: "http://cdn.datos.gob.mx/qa"
twitter_username: jekyllrb
twitter_text: "Descarga y utiliza libremente datos abiertos que el Gobierno de la República genera y recolecta. @GobRep @DatosGobMx"
github_username:  mendozagioo

# Build settings
markdown: kramdown
gems: ['jekyll-redirect-from']